### ISSUE TITLE
Adding option in installation.sh to specify custom port for lighttpd

### ISSUE THREAD

**Issue by bive242** [wiedehopf/graphs1090#1]
First, great set of graphs!
I migrated my setup from an RPi3+ to a NUC when I got my airspy mini. The RPi3+ didn't keep up and the NUC is way more powerful. 
The NUC is used for various tasks (running debian stretch). I had to install dump1090-fa (and lighttpd) on a different port (I choose 8111) and that didn't work so well with your install.sh-script. I had to make some changes in the script to suit my needs.

I suggest that you add an option to specify a port used by lighttpd to install.sh to make the process smoother.

**Comment by wiedehopf** [comment]
If you change the lighttpd port in the main lighttpd config then the graphs subconfig should just work on that port.

I don't see much need to specify a port and would rather leave different lighttpd configurations to the user.

Why don't you post your configuration here and i'll leave the issue open for others to find or maybe add it to the Wiki.
