### ISSUE TITLE
Error while using Installation Script / Read-only file system

### ISSUE THREAD

**Issue by DunkelBlauer** [wiedehopf/graphs1090#10]
Using: Pi24 with Dump1090 Dev 1.15
-----
Hi Widehopf thanks for this addon,
i'am unable to run the installation script out of the box.

Output:
```
pi@raspberrypi:~ $ sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/wiedehopf/graphs1090/master/install.sh)"
mkdir: cannot create directory ‘/usr/share/graphs1090’: Read-only file system
mkdir: cannot create directory ‘/var/lib/graphs1090’: Read-only file system
touch: cannot touch '/usr/share/graphs1090/installed/rrdtool': No such file or directory
touch: cannot touch '/usr/share/graphs1090/installed/collectd-core': No such file or directory
[.....]
```

Thanks for any hints,
Cheers

**Comment by wiedehopf** [comment]
Install the bundle below, it will also fix the read-only problem cause by fr24feed or the fr24 sd-card image.
https://github.com/wiedehopf/adsb-scripts/wiki/Bundle-install-for-dump1090fa

**Comment by wiedehopf** [comment]
Alternatively run these two commands to fix the fr24feed bug:

```
sudo mount -o remount,rw /
sudo sed -i -e 's?$(mount | grep " on / " | grep rw)?{ mount | grep " on / " | grep rw; }?' /usr/lib/fr24/fr24feed_updater.sh &>/dev/null
```

**Comment by DunkelBlauer** [comment]
Thank you,
just installed the bundle and the installation script is also working!
