### ISSUE TITLE
Possible typo: libpython2.7 referenced twice

### ISSUE THREAD

**Issue by Ve2mrx** [wiedehopf/graphs1090#12]
in:
https://github.com/wiedehopf/graphs1090/blob/b6ef9c5ae24020dd13949e7aa8b347112aefd4df/install.sh#L32
```
	if ! dpkg -s libpython2.7 2>/dev/null | grep 'Status.*installed' &>/dev/null \
		|| ! dpkg -s libpython2.7 2>/dev/null | grep 'Status.*installed' &>/dev/null
	then
		apt-get update
		apt-get install -y 'libpython2.7'
		apt-get install -y 'libpython3.7'
```
libpython2.7 is referenced twice, but the following lines install 2.7 AND 3.7. Maybe the second should be 3.7?

Martin

**Comment by wiedehopf** [comment]
That's more a shotgun approach anyway.
But yes you are correct.

On debian testing it needs python3.

I'll just try to install both ... a little bit of crud never hurt.
