### ISSUE TITLE
Add cpu core temps to graphs1090

### ISSUE THREAD

**Issue by jrsphoto** [wiedehopf/graphs1090#13]
I travel in a motorhome and when parked I have a pi4 and Airspy mini in a mast-mounted outdoor enclosure just below my antenna. This entire setup is powered using POE from inside the RV.  A temp sensor in the box allows me to monitor the temp of the box itself and turn on a fan if things get too hot.

I just installed graphs1090 and it seems like a great tool for long-term tuning of piaware/airspy_adsb.   After thinking about it, I thought It would be nice to track CPU core temp as well.  Any chance you could also add the CPU temp to the graphs?

`cat /sys/class/thermal/thermal_zone0/temp` divided by 1000 gives you the CPU temp in Celsius.

**Comment by wiedehopf** [comment]
Scroll down?
Already has a temperature graph.

**Comment by jrsphoto** [comment]
Well now I feel like a dumbass.  Lol.  This is why I should not stay up late.

**Comment by wiedehopf** [comment]
Glad you found it :)
