### ISSUE TITLE
CPU Utilization graph is very difficult to read

### ISSUE THREAD

**Issue by MikeyMoMo** [wiedehopf/graphs1090#14]
That graph uses green, green and green for the colors.  A one line change will make the "Other" graph a yellow/orange color but make it whatever you want.

Search for "CPU Utilization" to home in on it.  Nice tool!  SO much data!!

This is in /usr/share/graphs1090/graphs1090.sh

        rrdtool graph \
                "$1.tmp" \
                --start end-$4 \
                $small \
                --title "$3 CPU Utilization" \
                --units-exponent 0 \
                --vertical-label "CPU %" \
                --lower-limit 0 \
                --upper-limit 5 \
                $upper \
                --right-axis 1:0 \
                --left-axis-format "%.0lf" \
                --right-axis-format "%.0lf" \
                "DEF:demod=$(check $2/dump1090_cpu-demod.rrd):value:AVERAGE" \
                "CDEF:demodp=demod,10,/" \
                "DEF:reader=$(check $2/dump1090_cpu-reader.rrd):value:AVERAGE" \
                "CDEF:readerp=reader,10,/" \
                "DEF:background=$(check $2/dump1090_cpu-background.rrd):value:AVERAGE" \
                "CDEF:backgroundp=background,10,/" \
                $airspy_graph1 \
                $airspy_graph2 \
                $airspy_graph3 \
                "AREA:readerp#008000:USB" \
                "AREA:backgroundp#FFC000:Other:STACK" \                     # Change the "Other" color here to a yellow/orangey color.  Was 00C000
                "AREA:demodp#$GREEN:Demodulator\c:STACK" \
                "COMMENT: \n" \
                --watermark "Drawn: $nowlit";
        mv "$1.tmp" "$1"
        }

**Comment by wiedehopf** [comment]
It's not that important to distinguish those.

I want to keep with the original theme.
Primarily i really don't even want to change this project at all unless i have to.

I'm well aware on how to change the colors, but thank you :)
