### ISSUE TITLE
Linux VM network interface name

### ISSUE THREAD

**Issue by cwichura** [wiedehopf/graphs1090#15]
I run my ADS-B tracking in a Debian Buster VM, rather than on a RPi.  USB passthrough of the SDR works just fine under KVM, and I save the Watts consumed by a separate device by running on a VM host that I already have running 24x7 for other local services anyway.

Debian Buster udev rules rename the vertio-based network interface to ens18.  I had to manually add this to the collectd.conf file in the Interfaces section.  As I expect this is one of those things where you'd always be chasing additions (a RHEL/CentOS VM would name it differently again), maybe consider making this auto-adapt?  Maybe the install.sh script does a little magic to suss out the active interface and then updates a placeholder anchor in collectd.conf itself.  Or just not worry about filtering to specific interfaces and let collectd.conf collect all, since running in a VM or on a real RPi, you're unlikely to have extraneous interfaces anyway.  You'd just need to make sure your graph generation knows to skip the loopback interface data collected.

The VM also fails to capture CPU temperature, as that's reading an RPi-specific kernel stat which doesn't exist in a VM.  Maybe the install script could check for this and remove it from both the collectd.conf config and from the graph generation script?

Thanks

**Comment by wiedehopf** [comment]
Not to keen to work on this at the moment.

I can accept a PR i suppose.
But realistically this script won't work for all edge cases.
People on non debian system would have to install software on their own and there's no guarantee it'll work.
