### ISSUE TITLE
Change DB location

### ISSUE THREAD

**Issue by luciodaou** [wiedehopf/graphs1090#16]
Hello, on the readme there's a mention regarding rrd databases writing around 100 MB per hour.
> https://github.com/wiedehopf/graphs1090#reducing-writes-to-the-sd-card

Would it possible to change the DB location to any other external media?

On my setup, I have an external USB hard disk and old microSD cards connected on the RPi 3B for logging purposes, to avoid wearing the system microSD card.

**Comment by wiedehopf** [comment]
```
/etc/collectd/collectd.conf
```

```
##############################################################################
# Plugin configuration                                                       #
##############################################################################
<Plugin rrdtool>
    DataDir "/var/lib/collectd/rrd" 
```

**Comment by luciodaou** [comment]
@wiedehopf changing DataDir to `/mnt/usb/graph1090_rrd"` made it stop working. Check it out:
![Screenshot_2020-04-28 graphs1090 Performance Graphs](https://user-images.githubusercontent.com/53634214/80662576-fed72a80-8a67-11ea-9bcb-fc5401a2b6a5.png)

**Comment by wiedehopf** [comment]
oh you're correct graphs1090.sh has the other path hard-coded.

use a symlink that's easiest.

```
sudo systemctl stop collectd
sudo cp -T -a /var/lib/collectd/rrd /mnt/usb/graph1090_rrd
sudo mv /var/lib/collectd/rrd/ /var/lib/collectd/backup
sudo ln -s /mnt/usb/graph1090_rrd /var/lib/collectd/rrd/
sudo systemctl restart collectd
```

**Comment by luciodaou** [comment]
Ok, thanks, it worked!

Only an observation, when creating the symlink, I had to remove the last slash:
>`sudo ln -s /mnt/usb/graph1090_rrd /var/lib/collectd/rrd**/**`
became
`sudo ln -s /mnt/usb/graph1090_rrd /var/lib/collectd/rrd`
