### ISSUE TITLE
Some graphs do not generate if collectd interval is changed

### ISSUE THREAD

**Issue by trishmapow** [wiedehopf/graphs1090#19]
I recently added a Python plugin to collectd (Import "weather" in \<Plugin python\>) to collect some weather data and needed to increase the granularity so I set the global interval in collectd.conf to 5 (default was 60). This works fine for my weather data and the system graphs but almost all of the dump1090 graphs are now no longer showing. 
![image](https://user-images.githubusercontent.com/17211063/88503509-45133a00-d015-11ea-9840-b1ca6f30f543.png)

I'm very new to collectd/rrdtool, but ls -la shows the dump1090-localhost rrd files are still being updated, although with no/invalid data?
`pi@raspberrypi:/var/lib/collectd/rrd/localhost/dump1090-localhost $ rrdtool info dump1090_messages-positions.rrd
filename = "dump1090_messages-positions.rrd"
rrd_version = "0003"
step = 5
last_update = 1595823950
header_size = 3300
ds[value].index = 0
ds[value].type = "DERIVE"
ds[value].minimal_heartbeat = 10
ds[value].min = 0.0000000000e+00
ds[value].max = 8.0000000000e+03
ds[value].last_ds = "44761"
ds[value].value = NaN
ds[value].unknown_sec = 0`

Not sure what's happening, maybe something to do with the RRARows/RRATimespan but I don't fully understand yet. Would appreciate some help, thanks.

**Comment by wiedehopf** [comment]
you should look at the syslog ...
sudo journalctl --no-pager -u collectd

Good luck, i'm not sure i agree that you need more granularity for weather data.
Probably collectd isn't happy that it's getting the same value over and over because the stats.json is only updated every minute.
So in effect you only get a value every 20 data points. Not sure if there is a way to fix that with collectd.

**Comment by wiedehopf** [comment]
Closing as it's not an issue with graphs1090.

**Comment by trishmapow** [comment]
Thanks, I was checking `service graphs1090 status` which cut off the failure logs! You're right it doesn't like duplicate timestamps, my 2 second workaround was to add Interval 60 just for the python plugin. My weather script buffers historical data anyway so I don't lose any points.
