### ISSUE TITLE
Add graph last 1 Hours ?

### ISSUE THREAD

**Issue by disquette38** [wiedehopf/graphs1090#20]
Is it possible to add the last hour elapsed in the Performance Graphs display?

And for your information I was able to import the graphs of my old application adsb-receiver_2.6.3_dump1090-mutability_raspbian-stretch-lite by following your Backup and Restore advice (different architecture), then relaunch the script :
`sudo /bin/bash /usr/share/graphs1090/service-graphs1090.sh` 

**Thank you for your work @wiedehopf**  !

**Comment by wiedehopf** [comment]
Don't start the script like that ....

And no i will not add a 1h graph, the recorded data are not fine grained enough for that.
