### ISSUE TITLE
.rrd file only containd 1 Year

### ISSUE THREAD

**Issue by Conan179** [wiedehopf/graphs1090#21]
I have a strange behavior here, but this is not a bug from grah1090.
So my problem is that my .rrd file only contains 1 year of data.
If I restore from a backup from March 2020, as it is in the instructions, all data older than 1 year will simply be deleted.
I looked it up by comparing the .rrd files from / var / lib / collectd / rrd / localhost / dump1090-localhost folder that export.xml with the xml export files from the backup.
Can someone help me so that I can save all the data?

**Comment by wiedehopf** [comment]
https://github.com/wiedehopf/graphs1090#resetting-the-database-format

**Comment by Conan179** [comment]
I've already done it, but nothing.

**Comment by wiedehopf** [comment]
It's not gonna create data for the other 2 years.
The old database format used by adsb-receiver scripts only had 1 year.
