### ISSUE TITLE
Raspberry CPU temperature

### ISSUE THREAD

**Issue by jglerner** [wiedehopf/graphs1090#22]
As in the first group of graphs there is an odder number of graphs , I ask if is it feasible a new feature, a CPU temperature  graph. That should be very helpful. It seems that’s quite ease to implement this feature.At least for my needs that should be very useful. Thanks for the good job. Regards, Jacques 
PS I don’t know if it is the right place to ask a new feature but, for me, seems to be.

**Comment by wiedehopf** [comment]
![image](https://user-images.githubusercontent.com/6976172/98260776-ffef9400-1f83-11eb-8dca-5f4f929fda76.png)

There is such a graph already in the system graphs ... where it belongs.
