### ISSUE TITLE
Bandwidth Usage graph does not populate.

### ISSUE THREAD

**Issue by peatrick** [wiedehopf/graphs1090#24]
![image](https://user-images.githubusercontent.com/26148066/103120222-db8b6c00-4644-11eb-8157-37922c76b08a.png)
All other graphs appear fine, have attempted to reinstall multiple times using the following command: `sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/wiedehopf/graphs1090/master/install.sh)"` but does not appear to resolve things.  Unsure what else I may be doing incorrectly, as I've recently migrated from RPi (ARM) running Raspbian 10 Lite to an old PC (x86_64) running pure Debian 10.  Thanks in advance for any assistance.  Perhaps it's just a quirk of this old hardware.
```
       _,met$$$$$gg.          user@hangar.air.example.com
    ,g$$$$$$$$$$$$$$$P.       ------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 10 (buster) x86_64
 ,$$P'              `$$$.     Host: EL1330
',$$P       ,ggs.     `$$b:   Kernel: 4.19.0-13-amd64
`d$$'     ,$P"'   .    $$$    Uptime: 1 day, 21 hours, 25 mins
 $$P      d$'     ,    $$P    Packages: 1767 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.0.3
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/0
 Y$$.    `.`"Y$$$$P"'         CPU: AMD Athlon 2850e (1) @ 1.800GHz
 `$$b      "-.__              GPU: NVIDIA GeForce 6150SE nForce 430
  `Y$$                        Memory: 665MiB / 1740MiB
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```

**Comment by wiedehopf** [comment]
```
<Plugin "interface">
    Interface "eth0"
    Interface "wlan0"
    Interface "enp0s10"
    Interface "enp1s10"
    Interface "enp0s25"
    Interface "enp1s25"
    Interface "wlp3s0"
    Interface "wlp2s0"
    Interface "wlp1s0"
    Interface "wlp0s0"
    Interface "eno0"
    Interface "eno1"
</Plugin>
```

/etc/collectd/collectd.conf

Just change the name of one of the interfaces in the file, you can find the names of your interfaces like this
```
ip l
```

Then restart the collectd service.

**Comment by peatrick** [comment]
You are amazing, thanks you -- silly neophyte mistake, obviously **enp0s7** wasn't on the default list.  Now resolved.  Will it populate the past 2+ days of back data, or was it more than a simple display issue?  Either way, you've resolved my issue within a matter of seconds.  Thank you for the incredible project.  Much obliged, sir.  Stay safe, happy happy joy joy.

**Comment by wiedehopf** [comment]
No that's the data collection part.

I could probably script something for that which deals with arbitrary names.

**Comment by peatrick** [comment]
Now that i know how to resolve it, it's really quite a simple fix -- i thought i read through everything available i could find, but still wasn't able to make sense of your quick-fix.  Cannot thank you enough for helping to resolve that nagging issue.  Appreciate your efforts for this community.

**Comment by the-jeffski** [comment]
Found this when looking a why I couldn't see any stats for bandwidth.  I can see the interface is listed in the conf file and can see an rrd file created under its ID but the chart is just a flat line.  Any ideas?  Could it be scale?
![image](https://user-images.githubusercontent.com/63499439/120627832-f8ca2f00-c45b-11eb-9f31-84a2ff208577.png)

**Comment by wiedehopf** [comment]
what's the rrd filename?

**Comment by wiedehopf** [comment]
looks like the rrd has only zeros in it.
you have other interfaces or other interface rrd files?

**Comment by the-jeffski** [comment]
So my collectd has:  <Plugin "interface">
        Interface "wlxa0f3c11fb3ad"
        Interface "enxb827eb050f57"
	Interface "eth0"
	Interface "wlan0"
	Interface "enp0s25"
	Interface "enp1s25"
	Interface "wlp3s0"
	Interface "wlp2s0"
	Interface "wlp1s0"
	Interface "wlp0s0"
	Interface "eno0"
	Interface "eno1"
</Plugin>

Interface 4 is the external wifi  and I have marked down the wlan0 so its not used.
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enxb827eb050f57: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether b8:27:eb:05:0f:57 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DORMANT group default qlen 1000
    link/ether b8:27:eb:50:5a:02 brd ff:ff:ff:ff:ff:ff
4: wlxa0f3c11fb3ad: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether a0:f3:c1:1f:b3:ad brd ff:ff:ff:ff:ff:ff

And in the folder I can see /var/lib/collectd/rrd/localhost/interface-wlxa0f3c11fb3ad/

**Comment by wiedehopf** [comment]
Yeah seems collectd isn't collecting data properly from that interface.
You could try reducing the clutter in the collectd.conf so it only does your interface.

Regardless this is a collectd issue in some way or form, check the syslog (see the reame section on how to report bugs ... just the journalctl is sufficient).
