### ISSUE TITLE
collectd Warning No JSON object could be decoded

### ISSUE THREAD

**Issue by bondskin** [wiedehopf/graphs1090#25]
Hello, 

On my raspberry Pi I am getting every minute the following error message in my syslog
collectd
raspberrypiwatch
Warning
No JSON object could be decoded

Is there anything I can suspend or fix to get rid of it?

**Comment by wiedehopf** [comment]
That's not even close to enough info about your setup .....

But likely you can edit /etc/collectd/collectd.conf and put a # in front of URL or URL_978 to stop collectd from trying and collect the associated data.

**Comment by bondskin** [comment]
sorry @wiedehopf to be so limited and cryptic, but that's all I see in the syslog. I think all graphs appear correctly.

But your recommendation did the trick, thank you!
