### ISSUE TITLE
FFT Graph

### ISSUE THREAD

**Issue by Andechs75** [wiedehopf/graphs1090#26]
Hi there,
first of all I have to thank you very much for your work! I see your Name everywhere if i search a solution when i'm getting stucked with my Pi.
Well i have a suggestion for some new Graphs. Might it possible to generate a graph like an FFT? Something like Level-bins or Range-bins over a certain time.
regards,
Volker

**Comment by wiedehopf** [comment]
Well the graphs already have something like that.
That's what the quartiles tell you more or less.

Fixed bins are problematic as they don't fit for everyone.
I'd somewhat like to avoid saving more data ... well maybe.
That would probably be something like 8 bins ... 0-40 nmi and so forth.
Then display those as a stacked solid graph?
I gotta admit it's somewhat i've thought about before ... i'll tink about it some more.

**Comment by Andechs75** [comment]
![fft](https://user-images.githubusercontent.com/69108698/104135540-62547e80-5391-11eb-8ce0-cde2375deae5.jpg)

Maybe give us a graph with some bins where you could enter the borders by input field or config file (like tar). The chooseable data will be caunted into the bins for a spezific duration or by pressing "start stop reset". I'm pretty sure you don't wan't to implement SQL;o)

A binned Graph could be used for a variety of things. Currently I get the intel that 8% of my Signals are stronger than -3dB and the strongest would be -1.4dB. So is it one Signal at -1.4 and the other 7.99% are below -2.8?

Maybe there is a way to export some data into a *.csv? So I can play with it in eggsel. I'm really not familiar with pi programming ;o) I only program robots for my part.. So if you could give me a hint how the get the data

**Comment by wiedehopf** [comment]
You haven't looked at the graphs carefully enough then :)
Check the green area, it represent the 50% in the middle (split by a line).
So combined that gives you data for all the quartiles.

If you want to churn the data yourself ... process /run/dump1090-fa/aircraft.json
