### ISSUE TITLE
[Feature Wish] Open in a new Tab

### ISSUE THREAD

**Issue by Dtrieb** [wiedehopf/graphs1090#28]
https://github.com/wiedehopf/graphs1090/blob/30cbb24203ffce3e9d73c3c494f1d4738007ebea/html/index.html#L188

Please open this Link in a new Tab.

**Comment by wiedehopf** [comment]
I'm confident people can figure out how to open links in a new tab on their own.

Holding Ctrl while clicking is usually one possibility, then there is the right click menu as well.
Middle mouse button might also do the trick.

Feel free to modify your local installation.
