### ISSUE TITLE
Graph: ADS-B Msg Rate / AC is off scale

### ISSUE THREAD

**Issue by w4tme** [wiedehopf/graphs1090#30]
I am running the latest 1090Graph as of 3/22/2021 and recently optimized my system for higher message rates.  Below is an image from the aforementioned graph for the 8 hour period over night.  As you can see the messages per aircraft (blue) is off scale.  The data indicates the max was 28.9, but the drawn blue line is maxing out at 30.

![Screen Shot 03-22-21 at 08 15 AM](https://user-images.githubusercontent.com/5146674/111988726-3b2fd100-8ae7-11eb-8b23-f0d38d015f5f.PNG)

**Comment by wiedehopf** [comment]
After multiple people nitpicking about this graph ... some minor changes.

https://github.com/wiedehopf/graphs1090/commit/38bf8fbbe5e6528054d99de3868830437c92a5db

**Comment by w4tme** [comment]
Thank you.  I really appreciate all you do.
