### ISSUE TITLE
ADS-B Message Rate per Aircraft graph does not show a value for AC Seen/Tracked (RHS)

### ISSUE THREAD

**Issue by w4tme** [wiedehopf/graphs1090#34]
In the ADS-B Message Rate per Aircraft graph does not show a max value for Aircraft Seen/Tracked (RHS) that is in the legend.  I would like to use this data (in addition to other data) to optimize the gain setting for my AirSpy. 

![Screen Shot 03-26-21 at 08 59 AM](https://user-images.githubusercontent.com/5146674/112635183-dee3ee80-8e11-11eb-88e8-6cf49c6b29a4.PNG)

**Comment by wiedehopf** [comment]
There are other graphs that show a maximum for the number of aircraft seen.
Thus adding it here seems redundant and i won't add it.
