### ISSUE TITLE
Recent addition of systemd warning

### ISSUE THREAD

**Issue by mymatenige** [wiedehopf/graphs1090#36]
Following commit a924eaac552ab077891d3f75f5fd6b611cdadb5b, I receive a warning from systemd every day at 23:42 when the job in /etc/cron.d/collectd_to_disk runs:

> Warning: The unit file, source configuration file or drop-ins of collectd.service changed on disk. Run 'systemctl daemon-reload' to reload units.

This can be resolved with "systemctl daemon-reload" until the next reboot and then it returns.

Can this be resolved permanently in graphs1090?  Thanks.

**Comment by wiedehopf** [comment]
That's not a graphs1090 issue, the dropin file is only created on install.

Probably an issue with your systemd version.

**Comment by mymatenige** [comment]
Okay, I'll have a dig.  I'm running the latest Pi OS with all of the patches.

**Comment by mymatenige** [comment]
Steps to reproduce:

- Fresh install of Pi OS.  Full updated.
- Install PiAware
- Install graphs1090
- Reboot
- Run "sudo /bin/systemctl restart collectd" and the warning shows
- Run "sudo /bin/systemctl daemon-reload"
- Run "sudo /bin/systemctl restart collectd" and the warning does not show

Trying to determine why systemd would consider collectd.service to have changed following a reboot.

**Comment by wiedehopf** [comment]
https://github.com/systemd/systemd/issues/13634

I think that's the issue popping up?
Anyhow it's safe to ignore.
