### ISSUE TITLE
Undefined Graph Scale

### ISSUE THREAD

**Issue by Bartholomew22** [wiedehopf/graphs1090#37]
There are 3 graphs that have an unlabeled scale on the right that is different from the labeled scale on the left.  I could not find a description in the read me file.  What do those unlabeled scales represent?  The graphs are ADS-B Message Rate, ADS-B Message Rate / Aircraft, and ADS-B Maxima.

**Comment by wiedehopf** [comment]
RHS means right hand side.
See the legens.
