### ISSUE TITLE
Network Bandwidth not showing when external rather than onboard used

### ISSUE THREAD

**Issue by the-jeffski** [wiedehopf/graphs1090#38]
I've had issues with packet loss from the onboard RPi3 wifi so went back to using an old wifi stick.  From then the bandwidth graph has not shown any data. 

![image](https://user-images.githubusercontent.com/63499439/120640790-ca078500-c46a-11eb-8c16-55e33a2b380c.png)

Journal log  https://pastebin.com/HS6PHyEG 

collectd has: <Plugin "interface">
Interface "wlxa0f3c11fb3ad"
Interface "enxb827eb050f57"
Interface "eth0"
Interface "wlan0"
Interface "enp0s25"
Interface "enp1s25"
Interface "wlp3s0"
Interface "wlp2s0"
Interface "wlp1s0"
Interface "wlp0s0"
Interface "eno0"
Interface "eno1"
Interface 4 is the external wifi and I have marked down the wlan0 so its not used.

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enxb827eb050f57: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
link/ether b8:27:eb:05:0f:57 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DORMANT group default qlen 1000
link/ether b8:27:eb:50:5a:02 brd ff:ff:ff:ff:ff:ff
4: wlxa0f3c11fb3ad: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
link/ether a0:f3:c1:1f:b3:ad brd ff:ff:ff:ff:ff:ff

And in the folder I can see /var/lib/collectd/rrd/localhost/interface-wlxa0f3c11fb3ad/

Nothing on the journal log mentions the interface though.

**Comment by wiedehopf** [comment]
As i said it's a collectd issue, graphs1090 is not at fault.
Another collectd version might work.

What system are you running anyhow with those interface names?
Maybe just start over: https://github.com/wiedehopf/adsb-wiki/wiki/Raspbian-Lite:-ADS-B-receiver

**Comment by jeffski10** [comment]
Its a  Pi 3 Model B Rev 1.2 running Buster .  The USB stick is a RTL8192CU 802.11n WLAN Adapter. 

Was thinking a re-install may be an option.  Would the backup of the graph data just restore that but ignore the rest so I don't end up with getting the same issue back?

**Comment by the-jeffski** [comment]
Its a Pi 3 Model B Rev 1.2 running Buster . The USB stick is a RTL8192CU 802.11n WLAN Adapter.

Was thinking a re-install may be an option. Would the backup of the graph data just restore that but ignore the rest so I don't end up with getting the same issue back?

**Comment by wiedehopf** [comment]
You can always delete that RRD file but i doubt it's the cause of the issue.
I suppose you could just stop collectd servie and delete that rrd file ... see if that helps.
Note that when collectd is stopped the rrd will be gzipped and in the /var/lib ... folder (assuming a current version).

I haven't seen this issue with Raspbian at all ... you can try apt update; apt dist-upgrade before doing a reinstall.
Somehow i doubt this issue can be fixed by a reinstall.

Yeah try this first:
```
sudo systemctl stop collectd
sudo rm  /var/lib/collectd/rrd/localhost/interface-wlxa0f3c11fb3ad/ -rf
sudo systemctl restart collectd
```

**Comment by the-jeffski** [comment]
OK, So tried an update and then the restart.  I can see data is collecting still but lighttpd has failed now.   
Tried to run the install script again as it reports an issue connecting to  dump978   which I don't have a receiver for

Job for lighttpd.service failed because the control process exited with error code.
See "systemctl status lighttpd.service" and "journalctl -xe" for details.
ERROR on line number 192

**Comment by wiedehopf** [comment]
> Tried to run the install script again as it reports an issue connecting to dump978 which I don't have a receiver for

That's fairly normal and shouldn't be an issue.

lighttpd not working well check the journalctl log for it and post it .. just it failing is not something i can determine why it's not starting.

**Comment by the-jeffski** [comment]
I get this when trying to start it.  
lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-06-03 14:20:52 BST; 5s ago
  Process: 29677 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=255/EXCEPTION)

Jun 03 14:20:52 flightradar systemd[1]: lighttpd.service: Service RestartSec=100ms expired, scheduling restart.
Jun 03 14:20:52 flightradar systemd[1]: lighttpd.service: Scheduled restart job, restart counter is at 5.
Jun 03 14:20:52 flightradar systemd[1]: Stopped Lighttpd Daemon.
Jun 03 14:20:52 flightradar systemd[1]: lighttpd.service: Start request repeated too quickly.
Jun 03 14:20:52 flightradar systemd[1]: lighttpd.service: Failed with result 'exit-code'.
Jun 03 14:20:52 flightradar systemd[1]: Failed to start Lighttpd Daemon.

All I see in the journal is the  Can't connect to 978 source (127.0.0.1:28380). Waiting 5 second...   errors when I run . Is there another log?

**Comment by wiedehopf** [comment]
No ... you just go up int he log until you find the error.
```
sudo journalctl -u lighttpd -e
```

**Comment by wiedehopf** [comment]
What log is the can't connect to 978 thing? .... please you need to share raw logs (as you don't extract the relevant parts)

**Comment by the-jeffski** [comment]
Log for Lighttpd  https://pastebin.com/uBFamXet 
Log with the 978 error which just shows in the journal https://pastebin.com/VXQp12zX

**Comment by wiedehopf** [comment]
The 978 error is for 978 ... disable it in the rbfeeder.ini if you don't run 978 ....

The lighttpd error is most easily fixed by installing tar1090 ... i've got some workaround for common issues: https://github.com/wiedehopf/tar1090#tar1090

**Comment by the-jeffski** [comment]
Great, back and running - did have tar1090 installed already so maybe the apt update knocked it out. 

Graph is still flat lining.  I see there is a plugin for logging for collect.d  https://collectd.org/wiki/index.php/Plugin:LogFile  Is this worth adding to see if anything is captured?

**Comment by wiedehopf** [comment]
lighttpd stopped working because the dump1090-fa update made an update and the lighttpd conf for it wasn't updated because the file had been changed by tar1090.
pretty complex interaction. i wouldn't modify config files for dump1090-fa but they are doing stupid redundant stuff which break lighttpd so i didn't have much of a choice.

I have no clue why this stuff isn't working for you ....
It's probably the way collectd is getting the data transferred isn't working.
The logfile plugin ..... i'd assume provides the same irrelevant output as journalctl -u collectd.

Really it's querying how much data has been transferred on that interface and somehow getting back zero.
That's not an error even if it's the wrong value so you wouldn't see an error.

**Comment by wiedehopf** [comment]
Most likely thing would be that you're actually using another interface for network data.....

**Comment by the-jeffski** [comment]
OK, well thanks for your help in debugging this through.  Have a feeling I'll just leave the graphc like it is for now rather than try any rebuild as its likely to end up in the same spot.  Just odd. Will close this off as its obviously not a error on the graphs1090.

**Comment by the-jeffski** [comment]
Just a comment in case anyone else has the same issue and finds this ticket, I have resolved it now. I deleted /var/lib/collectd/rrd/localhost/interface*  so no interface collection files existed, rebooted and then it all sprung to life. Not sure why but that seemed to work.
