### ISSUE TITLE
Disk usage

### ISSUE THREAD

**Issue by maverick464** [wiedehopf/graphs1090#39]
Hi @wiedehopf, I installed latest versione of your dashboard and I noticed that disk usage is increasing day by day as shown in pic attached. How can I stop this behavior? I'm not getting why so many MBs are saved, and where.

![system-localhost-df_root-7d](https://user-images.githubusercontent.com/86149089/123526542-e6e55000-d6d8-11eb-864c-fe1cce713530.png)

**Comment by wiedehopf** [comment]
It's not due to the graphs, i can guarantee you.
Graph data is kept here:
```
du -sh /var/lib/collectd
```

You'll have to figure out what is using disk space yourself.
Maybe try:
```
sudo apt install iotop
sudo iotop -a
```

I'll still reply, but i'm closing this as it's not an issue with graphs1090.

**Comment by maverick464** [comment]
@wiedehopf thanks for the reply. I'll try your suggestion and I'll try to figure it out by myself. You can obviously close the issue. Thanks again

**Comment by wiedehopf** [comment]
Well it could always be some sort of logs like fr24feed?
If you turned those on?
Probably wouldn't be that much so i don't know.

Does iotop show something?

**Comment by maverick464** [comment]
I tried what you suggested but I'm honest, as I'm a newbie, I didn't understand much of what it was showing me.
Anyway, I made a clean install of: dump1090-fa, piaware, fr24feed, pfclient, rbfeeder and your graphs1090. Let's see how it works now....thanks for the time you spent on me.

**Comment by wiedehopf** [comment]
Follow this guide for a real clean install: https://github.com/wiedehopf/adsb-wiki/wiki/Raspbian-Lite:-ADS-B-receiver

**Comment by bctrainers** [comment]
If desired, you can `apt install ncdu` and type `ncdu`  for an ncurses based output of your largest directories. Otherwise,  you can use something like `du -ckx / | sort -rn | head`. My bet is that you have some logs not being rotated out.

**Comment by maverick464** [comment]
> Follow this guide for a real clean install: https://github.com/wiedehopf/adsb-wiki/wiki/Raspbian-Lite:-ADS-B-receiver

Thanks a lot for the guide. I’ll save it to my favorites in case I need it in the future. I was looking for something like it but I ended up jumping between various forums. 

Anyway, back to the “issue” after the clean installation disk usage seems to be stable. 
mad you guessed it was probably some sort of log not being rotated. 

Thanks again

**Comment by maverick464** [comment]
> If desired, you can `apt install ncdu` and type `ncdu` for an ncurses based output of your largest directories. Otherwise, you can use something like `du -ckx / | sort -rn | head`. My bet is that you have some logs not being rotated out.

I’ll have a look into it as I’m completely unaware of what that is. Not very into programming, but good at copying and pasting understanding what I’m doing. 
Thanks a lot for the tip
