### ISSUE TITLE
Can't upgrade graphs1090 to newest version

### ISSUE THREAD

**Issue by bive242** [wiedehopf/graphs1090#41]
The install/upgrade scripts fails when the kernel can't be updated on the target system.

`adminuser@systemname:/var/log# bash -c "$(curl -L -o - https://github.com/wiedehopf/graphs1090/raw/master/install.sh)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0    352      0 --:--:-- --:--:-- --:--:--   351
100  8269  100  8269    0     0   8824      0 --:--:-- --:--:-- --:--:--  8824

Installing required packages: git rrdtool collectd-core

Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree
Reading state information... Done
collectd-core is already the newest version (5.8.1-1.3).
git is already the newest version (1:2.20.1-2+deb10u3).
rrdtool is already the newest version (1.7.1-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

Failed to install required packages: git rrdtool collectd-core
`
As you can see the required packages are all of the latest version for my platform (Buster x86_64) and the install-scripts fails due to the kernel can't be upgraded by the script:

`adminuser@systemname:/var/log# apt list --upgradable -a
Listing... Done
linux-image-amd64/oldstable 4.19+105+deb10u12 amd64 [upgradable from: 4.19+105+deb10u11]
linux-image-amd64/now 4.19+105+deb10u11 amd64 [installed,upgradable to: 4.19+105+deb10u12]
linux-image-amd64/oldstable 4.19+105+deb10u9 amd64
`

I guess that the latest kernel isn't required for graphs1090 to work properly. If it requires newer versions of git, rrdtool and collectd-core than what Debian buster can provide it would be beneficial with a more detailed error message or test explaining that you need to be running Debian bullseye.

Edit comments: Tried to make it look nice and readable, but it failed miserably...

**Comment by wiedehopf** [comment]
Three backticks on their own line, not one.
```
code
```

Anyhow try now .... 
It doesn't care about apt install.
It checks if the commands are available and apparently they didn't show that.

```
command -v git
command -v rrdtool
command -v collectd
```

**Comment by bive242** [comment]
Now it's working. Don't know if it was your changes or the fact that I was missing /usr/sbin in the path. Don't know how I could have missed that rather vital directory for my admin user 😁
