### ISSUE TITLE
SDR Gain Graph

### ISSUE THREAD

**Issue by VirusPilot** [wiedehopf/graphs1090#44]
Now that dump1090 v6.1 has adaptive-gain and adaptive-burst modes, I would welcome an additional graph showing the SDR gain values, maybe together with some related values like the actual dynamic range and the alternative noise value. Is that something that is easy to implement? For me it would certainly add significant value ...

**Comment by techfixpros** [comment]
Adaptive gain is working. Noise figures are shown in the signal level graphs.

![image](https://user-images.githubusercontent.com/7028086/160974752-f32b8a54-56c5-437d-925a-d8b66b429734.png)

![image](https://user-images.githubusercontent.com/7028086/160974776-05d8eb10-99ce-4c78-9aae-0ed1c61716fe.png)

![image](https://user-images.githubusercontent.com/7028086/160974812-6d1470c2-7e46-4227-a2c4-747359cb824c.png)

**Comment by wiedehopf** [comment]
just never closed the issue ... closed!
