### ISSUE TITLE
Is it possible to disable certain graphs?

### ISSUE THREAD

**Issue by turboboost55** [wiedehopf/graphs1090#47]
I am running on a RPi Zero, which of course if quite under-powered.  I am seeing fairly high CPU usage with Graphs1090 running, so was wondering if I could save a bit of CPU time by disabling data collection on certain graphs that I am not interested in.  Is that possible via the config file?

**Comment by wiedehopf** [comment]
The graph creation is probably way more CPU but there is no config option to disable certain graphs.

I think you can change how often the graphs are created.
Really ... just don't use a pi zero or remove graphs1090.

**Comment by turboboost55** [comment]
> I think you can change how often the graphs are created.

I suppose you're talking about the `DRAW_INTERVAL` setting.  I found out about that on [this helpful reddit thread](https://www.reddit.com/r/ADSB/comments/qakl3d/big_jump_in_cpu_usage_since_piaware_60_is_this/).  Increasing that value made a noticeable improvement.
