### ISSUE TITLE
Longer  Time Period for Graphs

### ISSUE THREAD

**Issue by cyberralf83** [wiedehopf/graphs1090#48]
This is a great plugin. Ive had it installed for +2.5 years. Is there any way to extend the graphs beyond 3 years, maybe 5 years or all time?
Thanks

**Comment by wiedehopf** [comment]
Yeah it would be possible.

I suppose it's not a bad idea, i'll look into it.

**Comment by wiedehopf** [comment]
You'll need to reset the database format as described here: https://github.com/wiedehopf/graphs1090#resetting-the-database-format
