### ISSUE TITLE
CPU Utilization

### ISSUE THREAD

**Issue by cwalker51** [wiedehopf/graphs1090#5]
The 2 CPU Utilization plot are inconsistent

(https://user-images.githubusercontent.com/49570318/59166158-44e77080-8adb-11e9-8573-582c45b33eb0.png)

![image](https://user-images.githubusercontent.com/49570318/59166176-7eb87700-8adb-11e9-8eba-aa3664ff1246.png)

ADS-B CPU Utilization is Larger than Overall CPU Utilization

Just an FYI.  Your charts helped me find a failing power supply. It went away for minutes at a time. The gaps on the graph identified processor not running.  It was up to hours by the time I got a new one.

**Comment by wiedehopf** [comment]
ADS-B CPU is percentage of one core, overall CPU is percentage of all cores combined.

ADS-B CPU is limited by single core performance so it makes sense to make it relative to one core.

**Comment by cwalker51** [comment]
Thanks, Makes perfect sense. 
    On Sunday, June 9, 2019, 11:06:01 PM PDT, wiedehopf <notifications@github.com> wrote:  
 
 
ADS-B CPU is percentage of one core, overall CPU is percentage of all cores combined.

ADS-B CPU is limited by single core performance so it makes sense to make it relative to one core.
