### ISSUE TITLE
graphs for 978 without dump1090

### ISSUE THREAD

**Issue by pebblebacon** [wiedehopf/graphs1090#51]
There are many 1090 sites around my area. Not many 978UAT sites.  Is there a way to get 978 maps only, and not 1090 as there would be no data?  RPI -Bullseye and at times the piaware sd image.

**Comment by wiedehopf** [comment]
so it's blank, not the end of the world :0

but yeah i can look into it.

**Comment by pebblebacon** [comment]
Lol. The 1090 are blank, yes.  But 978 graphs never populated with traffic
in the area.  Other CPU graphs are showing data correctly.

Good luck and thanks!

**Comment by wiedehopf** [comment]
978 should populate just fine.

**Comment by pebblebacon** [comment]
I will investigate further later. But for now, I must waste my day working.

**Comment by pebblebacon** [comment]
Alright, I've a done another install.  The graphs are now there.  Now, can you make an airplane appear?

**Comment by pebblebacon** [comment]
I've now got graphs.  
Keep up the great work.
