### ISSUE TITLE
Suggestion: Avoiding 'no space left on device' when running rrd-dump.sh for migration

### ISSUE THREAD

**Issue by AhrBee** [wiedehopf/graphs1090#53]
I was migrating a complete piaware installation from 32-bit Debian bullseye to 64-bit (completely fresh installation). I wanted to keep the 32-bit source running dump1090-fa for a while to compare performance (piaware shut down after migration from the source). Since it might be unlikely that someone would want to keep the source running after a migration, this situation might be rare. I thought I would share my experience with an unexpected failure (and resolution) if it would help anyone else.

When using the guide [backup and restore on different architecture](https://github.com/wiedehopf/graphs1090#backup-and-restore-different-architecture-for-example-moving-from-rpi-to-x86-or-the-other-way-around) in the source host. ran into a problem where /run (on tmpfs) ran out of space after `collectd` attempted to restart after the command 
```
/usr/share/graphs1090/rrd-dump.sh /var/lib/collectd/rrd/localhost/
```

Symptom:
```
May 13 10:19:35 pi-outside collectd[28906]: copying DB from disk to /run/collectd
May 13 10:19:35 pi-outside collectd[28910]: cp: error writing '/run/collectd/localhost/disk-sda/disk_octets.xml': No space left on device
May 13 10:19:35 pi-outside collectd[28910]: cp: error writing '/run/collectd/localhost/disk-sda/disk_merged.xml': No space left on device
May 13 10:19:35 pi-outside systemd[1]: collectd.service: Control process exited, code=exited, status=1/FAILURE
May 13 10:19:35 pi-outside collectd[28918]: readback didn't complete, no writeback of /run/collectd to disk!
May 13 10:19:35 pi-outside systemd[1]: collectd.service: Control process exited, code=exited, status=1/FAILURE
May 13 10:19:35 pi-outside systemd[1]: collectd.service: Failed with result 'exit-code'.
May 13 10:19:35 pi-outside systemd[1]: Failed to start Statistics collection and monitoring daemon.
```
It seems that the `readback.sh` and `writeback.sh` take all files in `/var/lib/collectd/rrd/localhost/` which now include all the rrd dumps (*.xml) and attempts to write them all to `/run/collectd/...` when attempting collectd service startup. I have several years' worth of data for graphs1090, and that blew away the `/run` tmpfs causing collectd to not run anymore.

I copied off and removed the xml files from the regular filesystem, removed them from the archives, and was able to restart collectd in the source OK. 

One suggestion for migrations: change the process in the `/usr/share/graphs1090/rrd-dump.sh`  to not starting `collectd.service` until the rrd dump files and folders are moved out. This will avoid potentially overruning the available tmpfs storage for `/run`
```
# Add this before starting collectd.service
cd /var/lib/collectd/rrd
sudo /usr/share/graphs1090/gunzip.sh /var/lib/collectd/rrd/localhost
sudo tar -cz -f rrd.tar.gz localhost
find /var/lib/collectd/rrd/localhost -mindepth 2 -type f ! -name \*.rrd -delete
mv rrd.tar.gz /tmp
```

Another alternative would be to temporarily increase the size of `/run` with an entry in `/etc/fstab` and run your migration script, followed by deleting the `.xml` files in the `/run/collectd/` tree. 
```
# temporary add to /etc/fstab:
tmpfs /run tmpfs nosuid,noexec,size=256M 0  0
```

**Comment by wiedehopf** [comment]
Testing is welcome! :)

**Comment by AhrBee** [comment]
Nice - tested on a copy of my old source, worked just fine. Thanks!
