### ISSUE TITLE
Graphs with local timezone instead of UTC

### ISSUE THREAD

**Issue by sdadh01** [wiedehopf/graphs1090#57]
```rrdtool graph``` outputs with graphs in UTC. Some people (well, at least me) may prefer their graphs to be in their local timezone or maybe some other timezone altogether. A quick hack to do this is to add the following to /etc/default/graphs1090:

```
# set time zone for rrdtool graphs
export TZ=PST8PDT
```

Changing TZ to whatever timezone you want. Now when ```rrdtool graph``` runs it picks up $TZ and creates the graphs in the timezone that is set.

I realise this is not the prettiest solution - the export feels wrong but without it TZ is not passed onto rrdtool. There may be a better place to set this - but this works. 

Note that this does not affect collectd - it still dumps data to the RRD database in UTC because the collectd service is not running /etc/default/graphs1090. This only affects the graphs at build time - they end up with the timezone displayed in the 'Drawn: xxxxx' note at the bottom of a graph.

The changes to /etc/default/graphs1090 above result as in the example below after restarting using ```sudo systemctl restart graphs1090```:

![Screen Shot 2022-08-15 at 19 31 17](https://user-images.githubusercontent.com/1427263/184785731-2414eb25-fce1-4d88-9db0-4b6e3144c84f.png)

I can fork and PR if you want to include this or if you don't then that's fine with me too - I have my local hack ;-)

**Comment by wiedehopf** [comment]
You can just change the timezone for the system?

**Comment by wiedehopf** [comment]
collectd data is always in UTC it doesn't know anything else.

You would like something included in the readme?

**Comment by wiedehopf** [comment]
let me just do a commit and you can take a look if that's appropriate.

**Comment by sdadh01** [comment]
I prefer not change the timezone on the system to as all my other servers are UTC (as I think they should be - besides as a Brit living in the States I have to cling to my home time somehow ;-)). I just wanted the output from rrdgraph to be in local time - it makes more sense to me to see the nighttime dips in traffic be shown as at night time. 

Having the info in the readme would be great.

**Comment by sdadh01** [comment]
Readme info looks great - Vielen Dank!
