### ISSUE TITLE
Option to view specific days or compare days 

### ISSUE THREAD

**Issue by slvrscoobie** [wiedehopf/graphs1090#62]
I love this feature for my ADSB feeders, but I wondered if there is a way to plot the data for a specific day or dates if I wanted to compare historical data? Ie: how did Last Monday compare to this Monday. I can see it in the 7 days, but the averages, etc would be way easier to compare if I could either see just those 24 hours from 7 days ago or plot X and X-7 days. I assume number 2 would be much harder to code, but thought maybe I was missing something in being able to see 24 hours starting from X hours ago?

**Comment by bimmerdriver** [comment]
Assuming all of the data are saved, it would be great to be able to move backward or forward in time or to be able open a graph of any of the collected time scales at any point in time. For example, if you wanted to take a close look at a particular time of day.
