### ISSUE TITLE
second instance of Graphs1090 for 2nd decoder?

### ISSUE THREAD

**Issue by slvrscoobie** [wiedehopf/graphs1090#64]
Ive got 2 decoders now, one for high gain, and one for lower, and id love to see my info from Graphs1090 on the 2nd instance. 
Is this possible with the way the program is written? Tar1090 and Dump1090-fa both have been able to add the 2nd instance so I imagine its possible but I dont see where I could edit some of the install script or files to adjust for 31104, or 31105 that dump1090 is outputting, if thats even what your linking to.

**Comment by wiedehopf** [comment]
no
