### ISSUE TITLE
Dark mode still not dark enough ;-)

### ISSUE THREAD

**Issue by BebeMischa** [wiedehopf/graphs1090#66]
Very very thankful for the dark mode ;-)

Well, there still is too much of white beating my eyes at night...

Can you, please, get me rid of the white background? I will be very thankful...

![image](https://user-images.githubusercontent.com/73079275/236483366-4ba7c94b-d10c-4ab3-9649-34749e0d2705.png)

**Comment by wiedehopf** [comment]
Doesn't look like that for me, in doubt Ctrl-F5

**Comment by BebeMischa** [comment]
Sorry for the storm. ctrl+F5 did nothing, restart of the feeder did. ;-)
Anyway, thanks for the super fast response (y)
