### ISSUE TITLE
Stock Install - No signal graph

### ISSUE THREAD

**Issue by kevdel** [wiedehopf/graphs1090#7]
From a bare jessie image with dump1090-fa working fine I installed the graphs1090 code and all works well apart from the signal graph. I get a 404 error for the image on all time ranges (1h, 24h etc) on the http://localhost/graphs1090 page
 
No images with the name of signal in the /run/graphs1090 drrectory

**Comment by wiedehopf** [comment]
Some reduced functionality on jessie is to be expected, it's outdated.
Even stretch is the  old version now that buster is available.

Anyway let's see what the actual error is:
`sudo /usr/share/graphs1090/graphs1090.sh`

**Comment by wiedehopf** [comment]
Maybe just remove the associated database files and wait 10 minutes to see if it starts working:
```
sudo systemctl stop collectd
sudo rm /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_dbfs-*
sudo systemctl restart collectd
```

Sometimes collectd seems to screw up the database creation.

**Comment by kevdel** [comment]
`pi@777-300ER:~ $ sudo /usr/share/graphs1090/graphs1090.sh
26383 (process ID) old priority 0, new priority 19
619x324
619x324
619x324
619x324
619x324
1258x330
619x324
ERROR: unknown option '--left-axis-format'
mv: cannot stat '/run/graphs1090/dump1090-localhost-signal-24h.png.tmp': No such file or directory
1258x330
619x324
619x324
619x324
619x324
619x324
619x324`

**Comment by wiedehopf** [comment]
Ok, run the install script again in a couple of minutes.

Should be fixed.
Again you should really upgrade to Buster some day.

**Comment by kevdel** [comment]
fix is good.. thank you

working on the upgrade now! ;)

**Comment by wiedehopf** [comment]
I'd only recommend the upgrade via using a fresh sd-card image.

Updating inplace will most likely result in the system not working anymore.
