### ISSUE TITLE
number of messages received from beast via readsb not shown

### ISSUE THREAD

**Issue by harkwoodservices** [wiedehopf/graphs1090#76]
This could be a graphs1090 or a readsb thing.  I use your readsb to take data from a ModeS Beast, everything plots fine but the messages received seems to be incorrect.

![dump1090-localhost-local_trailing_rate-24h](https://github.com/wiedehopf/graphs1090/assets/63117890/e9dcdad7-10d7-48f3-bcf3-a2366d177086)

Graphs1090 seems to show virtually no messages, though I can generally see over 100 aircraft at any given time.  I don't know if readsb is not generating the correct data, or that graphs1090 is not picking it up correctly.  

The diagnostic info is below.

sudo journalctl --no-pager -u collectd | tail -n40
Feb 20 09:50:00 hsladmin-Macmini collectd[207445]: collectd: Stopping 1 write threads.
Feb 20 09:50:00 hsladmin-Macmini collectd[207445]: rrdtool plugin: Shutting down the queue thread.
Feb 20 09:50:00 hsladmin-Macmini systemd[1]: collectd.service: Deactivated successfully.
Feb 20 09:50:00 hsladmin-Macmini systemd[1]: Stopped Statistics collection and monitoring daemon.
Feb 20 09:50:00 hsladmin-Macmini systemd[1]: collectd.service: Consumed 1min 3.098s CPU time.
Feb 20 09:50:00 hsladmin-Macmini systemd[1]: Starting Statistics collection and monitoring daemon...
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "syslog" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "rrdtool" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "table" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "interface" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "cpu" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "aggregation" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "match_regex" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "df" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "disk" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: plugin_load: plugin "python" successfully loaded.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: Systemd detected, trying to signal readiness.
Feb 20 09:50:00 hsladmin-Macmini systemd[1]: Started Statistics collection and monitoring daemon.
Feb 20 09:50:00 hsladmin-Macmini collectd[1911036]: Initialization complete, entering read-loop.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911036]: Exiting normally.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911036]: collectd: Stopping 5 read threads.
Feb 20 09:50:33 hsladmin-Macmini systemd[1]: Stopping Statistics collection and monitoring daemon...
Feb 20 09:50:33 hsladmin-Macmini collectd[1911036]: collectd: Stopping 1 write threads.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911036]: rrdtool plugin: Shutting down the queue thread.
Feb 20 09:50:33 hsladmin-Macmini systemd[1]: collectd.service: Deactivated successfully.
Feb 20 09:50:33 hsladmin-Macmini systemd[1]: Stopped Statistics collection and monitoring daemon.
Feb 20 09:50:33 hsladmin-Macmini systemd[1]: Starting Statistics collection and monitoring daemon...
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "syslog" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "rrdtool" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "table" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "interface" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "cpu" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "aggregation" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "match_regex" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "df" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "disk" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: plugin_load: plugin "python" successfully loaded.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: Systemd detected, trying to signal readiness.
Feb 20 09:50:33 hsladmin-Macmini systemd[1]: Started Statistics collection and monitoring daemon.
Feb 20 09:50:33 hsladmin-Macmini collectd[1911259]: Initialization complete, entering read-loop.

sudo /usr/share/graphs1090/graphs1090.sh
1911762 (process ID) old priority 0, new priority 19
619x324
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
ERROR: invalid right-axis format expected scale:shift
mv: cannot stat '/run/graphs1090/dump1090-localhost-aircraft_message_rate-24h.png.tmp': No such file or directory
619x324
619x324
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
619x324
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-strong_signals.rrd not found! Associated graph will be empty!
1258x327
619x324
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_dbfs-signal.rrd not found! Associated graph will be empty!
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_dbfs-noise.rrd not found! Associated graph will be empty!
619x324
1258x327
619x324
619x324
619x324
619x324
619x324
619x324

I do have /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-remote_accepted.rrd generated by readsb, but not dump1090_messages-local_accepted.rrd

It's an old Intel MacMini running 22.04.1-Ubuntu

**Comment by wiedehopf** [comment]
Post the stats.json pls, it can be found in /run/readsb/stats.json or via http at /tar1090/data/stats.json

It's normal for local messages to not be there but the remote messages should be sufficient.
Can you specify the readsb command line part that ingests the data from the modes beast?

**Comment by harkwoodservices** [comment]
stats.json as requested...

{ "now" : 1708426495.0,
"aircraft_with_pos": 99, "aircraft_without_pos": 7, "aircraft_count_by_type": { "adsb_icao": 98, "adsb_icao_nt": 0, "adsr_icao": 0, "tisb_icao": 0, "adsc": 0, "mlat": 2, "other": 0, "mode_s": 6, "adsb_other": 0, "adsr_other": 0, "tisb_trackfile": 0, "tisb_other": 0, "mode_ac": 0, "unknown": 0},
"last1min":{"start":1708426435.0,"end":1708426495.0,"messages_valid": 258966,"position_count_total": 4179,"position_count_by_type": {"adsb_icao": 4147,"adsb_icao_nt": 0,"adsr_icao": 0,"tisb_icao": 0,"adsc": 0,"mlat": 32,"other": 0,"mode_s": 0,"adsb_other": 0,"adsr_other": 0,"tisb_trackfile": 0,"tisb_other": 0,"mode_ac": 0,"unknown": 0},"remote":{"modeac":0,"modes":51,"basestation": 0,"bad":0,"unknown_icao":0,"accepted":[51,0],"bytes_in": 3687943,"bytes_out": 11062998},"cpr":{"surface":0,"airborne":4152,"global_ok":3966,"global_bad":0,"global_range":0,"global_speed":0,"global_skipped":1,"local_ok":181,"local_aircraft_relative":181,"local_receiver_relative":0,"local_skipped":5,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":2455,"aircraft_json":39,"globe_json":0,"binCraft":0,"trace_json":0,"heatmap_and_state":5,"api_workers":0,"api_update":203,"remove_stale":40},"tracks":{"all":2,"single_message":2},"messages":258966,"max_distance":314540},
"last5min":{"start":1708426195.0,"end":1708426495.0,"messages_valid": 1310304,"position_count_total": 20087,"position_count_by_type": {"adsb_icao": 19980,"adsb_icao_nt": 0,"adsr_icao": 0,"tisb_icao": 0,"adsc": 0,"mlat": 107,"other": 0,"mode_s": 0,"adsb_other": 0,"adsr_other": 0,"tisb_trackfile": 0,"tisb_other": 0,"mode_ac": 0,"unknown": 0},"remote":{"modeac":0,"modes":177,"basestation": 0,"bad":0,"unknown_icao":0,"accepted":[177,0],"bytes_in": 18615484,"bytes_out": 55832343},"cpr":{"surface":0,"airborne":20062,"global_ok":19089,"global_bad":0,"global_range":0,"global_speed":0,"global_skipped":27,"local_ok":891,"local_aircraft_relative":891,"local_receiver_relative":0,"local_skipped":82,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":12463,"aircraft_json":198,"globe_json":0,"binCraft":0,"trace_json":0,"heatmap_and_state":28,"api_workers":0,"api_update":1061,"remove_stale":189},"tracks":{"all":21,"single_message":3},"messages":1310304,"max_distance":314540},
"last15min":{"start":1708425595.0,"end":1708426495.0,"messages_valid": 3890029,"position_count_total": 60289,"position_count_by_type": {"adsb_icao": 59626,"adsb_icao_nt": 0,"adsr_icao": 0,"tisb_icao": 0,"adsc": 0,"mlat": 663,"other": 0,"mode_s": 0,"adsb_other": 0,"adsr_other": 0,"tisb_trackfile": 0,"tisb_other": 0,"mode_ac": 0,"unknown": 0},"remote":{"modeac":0,"modes":1093,"basestation": 0,"bad":0,"unknown_icao":0,"accepted":[1093,0],"bytes_in": 55390692,"bytes_out": 166089843},"cpr":{"surface":0,"airborne":59865,"global_ok":56893,"global_bad":2,"global_range":0,"global_speed":0,"global_skipped":72,"local_ok":2733,"local_aircraft_relative":2733,"local_receiver_relative":0,"local_skipped":237,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":37126,"aircraft_json":599,"globe_json":0,"binCraft":0,"trace_json":0,"heatmap_and_state":88,"api_workers":0,"api_update":3200,"remove_stale":572},"tracks":{"all":78,"single_message":4},"messages":3890029,"max_distance":338440},
"total":{"start":1708364290.3,"end":1708426495.0,"messages_valid": 158598309,"position_count_total": 2658742,"position_count_by_type": {"adsb_icao": 2637085,"adsb_icao_nt": 0,"adsr_icao": 0,"tisb_icao": 0,"adsc": 0,"mlat": 21657,"other": 0,"mode_s": 0,"adsb_other": 0,"adsr_other": 0,"tisb_trackfile": 0,"tisb_other": 0,"mode_ac": 0,"unknown": 0},"remote":{"modeac":448,"modes":40114,"basestation": 0,"bad":0,"unknown_icao":0,"accepted":[40114,0],"bytes_in": 2269150951,"bytes_out": 6803865329},"cpr":{"surface":261,"airborne":2645471,"global_ok":2543229,"global_bad":149,"global_range":49,"global_speed":44,"global_skipped":2952,"local_ok":93856,"local_aircraft_relative":93856,"local_receiver_relative":0,"local_skipped":8496,"local_range":5,"local_speed":2,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":1617068,"aircraft_json":33142,"globe_json":0,"binCraft":0,"trace_json":0,"heatmap_and_state":5964,"api_workers":0,"api_update":126726,"remove_stale":34276},"tracks":{"all":3229,"single_message":113},"messages":158598309,"max_distance":397187}
}

**Comment by harkwoodservices** [comment]
The readsb config, all but lat/long...

# readsb configuration
# This is sourced by /etc/systemd/system/default.target.wants/readsb.service as
# daemon startup configuration.

RECEIVER_OPTIONS="--device 0 --device-type=modesbeast --beast-serial=/dev/ttyUSB0 --beast-modeac"
DECODER_OPTIONS="--lat 00.000000 --lon 0.000000 --max-range 450 --write-json-every 1 --modeac"
NET_OPTIONS="--net --decode-threads=2 --net-heartbeat 60 --net-ro-size 1250 --net-ro-interval 0.05 --net-ri-port 30001 --net-ro-port 30002 --net-sbs-port 30003 --net-bi-port 30004,30104 --net-bo-port 30005"
JSON_OPTIONS="--json-location-accuracy 2 --range-outline-hours 24"

**Comment by wiedehopf** [comment]
Yeah so that counts as remote messages and that's fine.
The stats.json is showing 80k in the last minute which means 1300msgs/s

Either the python code that collectd calls isn't putting it into the rrd file ... or the rrd file is somehow broken or it doesn't graph it properly.

Is the ADS-B Maxima graph working by chance?
![image](https://github.com/wiedehopf/graphs1090/assets/6976172/16f9b14d-f315-40f9-965f-94d8c88c811e)

**Comment by harkwoodservices** [comment]
Yes, that graph shows...
![dump1090-localhost-local_rate-24h](https://github.com/wiedehopf/graphs1090/assets/63117890/b7b05efb-b47e-47c9-a22a-29db88d35c71)

**Comment by harkwoodservices** [comment]
This is a new install, it was previously on a Pi, but that kept dropping the USB port to the beast.  The Pi didn't display the messages either, kind of hoped the rebuild onto a new box would fix it.

I've deleted the file, there is only a day or two's worth of data anyway.  There are dump1090_messages-remote_accepted_0.rrd and dump1090_messages-remote_accepted_1.rrd there too, just dump those too?  

Doesn't seem to have made a difference though...
The dump1090-localhost-aircraft_message_rate graphs are also missing, I guess because the data isn't there to build them.

**Comment by harkwoodservices** [comment]
As it's broken anyway, I took away the 

dump1090_messages-remote_accepted.rrd
dump1090_messages-remote_accepted_0.rrd
dump1090_messages-remote_accepted_1.rrd

all three were recreated, no difference.

**Comment by wiedehopf** [comment]
```

rrdtool dump /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-remote_accepted.rrd | head -n4000 | nc termbin.com 9999
```

There is no location in that file so uploading it there should be fine.
Then share the link.
This data will let me narrow down the issue (i hope).

**Comment by wiedehopf** [comment]
For reference, how it should look: https://termbin.com/c5rp

With it just being recreated yours will have a lot of NaN values but that's fine.

```
			<!-- 2024-02-20 12:23:00 CET / 1708428180 --> <row><v>1.5302930556e+03</v></row>
			<!-- 2024-02-20 12:24:00 CET / 1708428240 --> <row><v>1.4894750000e+03</v></row>
			<!-- 2024-02-20 12:25:00 CET / 1708428300 --> <row><v>1.4603388889e+03</v></row>
			<!-- 2024-02-20 12:26:00 CET / 1708428360 --> <row><v>1.4578541667e+03</v></row>
			<!-- 2024-02-20 12:27:00 CET / 1708428420 --> <row><v>1.4477694444e+03</v></row>
			<!-- 2024-02-20 12:28:00 CET / 1708428480 --> <row><v>1.4348472222e+03</v></row>
			<!-- 2024-02-20 12:29:00 CET / 1708428540 --> <row><v>1.3987097222e+03</v></row>
			<!-- 2024-02-20 12:30:00 CET / 1708428600 --> <row><v>1.3689194444e+03</v></row>
			<!-- 2024-02-20 12:31:00 CET / 1708428660 --> <row><v>1.3530333333e+03</v></row>
````
But it should show 1.3+03 for you for the 1300 messages per second.

**Comment by wiedehopf** [comment]
The stats.json looks close enough to my own ...
```
    "remote": {
      "modeac": 0,
      "modes": 87095,
      "basestation": 0,
      "bad": 0,
      "unknown_icao": 0,
      "accepted": [
        87095,
        0
      ],
      "bytes_in": 1562848,
      "bytes_out": 11175666
    },
```
your remote section for the last minute
```
"remote":{"modeac":0,"modes":51,"basestation": 0,"bad":0,"unknown_icao":0,"accepted":[51,0],"bytes_in": 3687943,"bytes_out": 11062998}```

**Comment by wiedehopf** [comment]
Actually that's weird.

**Comment by harkwoodservices** [comment]
Here you go https://termbin.com/ypsh 

It seems my values are somewhat lower 
 <row><v>2.2000000000e+00</v></row>

**Comment by wiedehopf** [comment]
Ok graphs1090 is fine.
I thought your stats.json was normal but somehow i must have looked at mine ... or something.

The stats.json is way off

Yeah i have no good explanation for that, readsb is somehow broken.

Why are you messing with --decode-threads ... remove that please :)

**Comment by harkwoodservices** [comment]
--decode-threads is history, I think that is a hangover from an even earlier Pi with an SDR dongle.  That was fried during a storm, took the SDR and the Pi out.

**Comment by wiedehopf** [comment]
Ok that was a readsb issue, please re-run the readsb install.
(i assume you used https://github.com/wiedehopf/adsb-scripts/wiki/Automatic-installation-for-readsb ?)

**Comment by wiedehopf** [comment]
Note that you likely aren't gonna see or use anything modeac ... might as well turn that off.
(tar1090 doesn't show any ModeAC stuff)

This is the fix .. just for completeness.
https://github.com/wiedehopf/readsb/commit/71e4ded3643028bae3ac2ddd285fb8b3e8767c6b

**Comment by harkwoodservices** [comment]
Yes, installed from the default scripts.  Oddly, now the beast isn't connecting... might go for a cold boot of everything.

**Comment by wiedehopf** [comment]
What's the log for the readsb service?
Anything useful?

I doubt it's related to the change i made.

Considering it was problematic with the pi ... it could just be an issue with the USB cable or the ModeS beast?

**Comment by harkwoodservices** [comment]
Hmm, the beast doesn't seem to be sending data now.  All I see is a few of these...

Feb 20 12:32:05 hsladmin-Macmini readsb[18930]: c->service null jahFuN3e

It was a new cable, is there a quick way to revert just to test?

**Comment by wiedehopf** [comment]
Oh no that's some issue with my code ... give me a moment.

**Comment by wiedehopf** [comment]
Reverted ... so you get data at least.
I'll have to look into the code more.

**Comment by wiedehopf** [comment]
Try the new version please.

**Comment by harkwoodservices** [comment]
Excellent work, that seems to have done the trick.  Beast is running and messages etc. appearing in the graphs1090.

**Comment by wiedehopf** [comment]
Would you do another test for me:

Unplug and plug the USB and check the readsb service log?

Might want to fix another potential issue.

**Comment by harkwoodservices** [comment]
If I unplug the beast and reattach, the log gets *lots* of...

Feb 20 13:27:00 hsladmin-Macmini readsb[43294]: c->service null jahFuN3e

...restarting readsb brings it back.

**Comment by harkwoodservices** [comment]
Seems to be fine now, this section of log covers the USB unplug and re-plug.
If you need modesbeast tests done in the future happy to help.

Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: Get client socket error failed.
Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: Shutdown client socket failed.
Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: Serial client closed unexpectedly, exiting!
Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: Serial client closed unexpectedly, exiting!
Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: [2024-02-20 13:37:17.451 GMT] Abnormal exit.
Feb 20 13:37:17 hsladmin-Macmini systemd[1]: readsb.service: Main process exited, code=exited, status=1/FAILURE
Feb 20 13:37:17 hsladmin-Macmini systemd[1]: readsb.service: Failed with result 'exit-code'.
Feb 20 13:37:17 hsladmin-Macmini systemd[1]: readsb.service: Consumed 2.106s CPU time.
Feb 20 13:37:32 hsladmin-Macmini systemd[1]: readsb.service: Scheduled restart job, restart counter is at 2.
Feb 20 13:37:32 hsladmin-Macmini systemd[1]: Stopped readsb ADS-B receiver.
Feb 20 13:37:32 hsladmin-Macmini systemd[1]: readsb.service: Consumed 2.106s CPU time.
Feb 20 13:37:32 hsladmin-Macmini systemd[1]: Started readsb ADS-B receiver.
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: invoked by: /usr/bin/readsb --device 0 --device-type=modesbeast --beast-serial=/dev/ttyUSB0  --lat xx --lon xx --max-range 450 --write-json-every 1 --net --net-heartbeat 60 --net-ro-size 1250 --net-ro-interval 0.05 --net-ri-port 30001 --net-ro-port 30002 --net-sbs-port 30003 --net-bi-port 30004,30104 --net-bo-port 30005 --json-location-accuracy 2 --range-outline-hours 24 --write-json /run/readsb --quiet
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: [2024-02-20 13:37:32.559 GMT] readsb starting up.
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: readsb version: 3.14.1611 wiedehopf git: acfc932 (committed: Tue Feb 20 14:19:10 2024 0100)
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: Using lat:   52.2266, lon:    0.1479
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: 30002: Raw TCP output port
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: 30005: Beast TCP output port
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: 30003: SBS TCP output ALL port
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: Running Mode-S Beast via USB.
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: 30001: Raw TCP input port
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: 30004: Beast TCP input port
Feb 20 13:37:32 hsladmin-Macmini readsb[70749]: 30104: Beast TCP input port

**Comment by wiedehopf** [comment]
All good ty very much.

This should very much increase reliability in case there is some issue with the device or USB as it'll just restart.
It just keeping going ... didn't like that at all :)

```
Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: Get client socket error failed.
Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: Shutdown client socket failed.
Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: Serial client closed unexpectedly, exiting!
Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: Serial client closed unexpectedly, exiting!
Feb 20 13:37:17 hsladmin-Macmini readsb[69345]: [2024-02-20 13:37:17.451 GMT] Abnormal exit.
```

That seems sane yes? :)

I'll close the issue, have a good day!
