### ISSUE TITLE
Missing graph aircraft_message_rate_24h

### ISSUE THREAD

**Issue by harkwoodservices** [wiedehopf/graphs1090#79]
Possibly related to the fix done to readsb under closed issue graphs1090 issue #76  ?

The /run/graphs1090/dump1090-localhost-aircraft_message_rate-24h.png is missing from graphs1090

debug output link.... https://pastebin.com/qxHeKHTS

**Comment by wiedehopf** [comment]
ERROR: invalid right-axis format expected scale:shift

no it's this error.
that's connected to the rrdtool version i suppose ...
I'd assume a very old system since i've never seen the error before.

**Comment by harkwoodservices** [comment]
New install of Ubuntu in the last week...

Linux hsladmin-Macmini 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

rrdtool --version
RRDtool 1.7.2  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Mar 17 2022 17:51:12

**Comment by wiedehopf** [comment]
Find /usr/share/graphs1090.sh
you're comfortable editing it?
You can easily get it back to normal by running the install so .. no real risk :)

This part is the issue.
```
		--right-axis "$ratio":0 \
```

modify to:
```
		--right-axis 10:0 \

```

**Comment by wiedehopf** [comment]
Or possibly you put something in the config for that?
```
# set custom left / right axis ratio
# leave blank for default of 10
lr_rate_per_aircraft=
```
Is that blank for you or you put something?

**Comment by harkwoodservices** [comment]
No, that is blank.  The graphs config is all default apart from changing the size to large from default, though that didn't make any difference.  Editing the file now...

**Comment by wiedehopf** [comment]
```
	if [ $ul_rate_per_aircraft ]; then upper="--rigid --upper-limit $ul_rate_per_aircraft"; else upper=""; fi
	if [ $lr_rate_per_aircraft ]; then ratio="$lr_rate_per_aircraft"; else ratio=10; fi
```
i'm not sure why i did it like that.

That's not how one should check for a blank variable ... 
I'll fix it i guess :)

**Comment by harkwoodservices** [comment]
Hmm, changed that line and I get...

ERROR: don't understand 'auto,/'

Revert the change and it's back to...

ERROR: invalid right-axis format expected scale:shift

**Comment by wiedehopf** [comment]
Hopefully fixed ... i assume your bash might be doing something different or something.

And i hope you edited wrong and that was the reason for your edit not fixing it.

**Comment by wiedehopf** [comment]
ERROR: don't understand 'auto,/'

Who did auto get in there?
Did you put that in?

**Comment by harkwoodservices** [comment]
nope, just changed the line as you said..line 240.
I've installed the latest changes from git, and I still get...

sudo /usr/share/graphs1090/graphs1090.sh
3280598 (process ID) old priority 0, new priority 19
1258x343
ERROR: invalid right-axis format expected scale:shift
mv: cannot stat '/run/graphs1090/dump1090-localhost-aircraft_message_rate-24h.png.tmp': No such file or directory
1258x343
1258x343
1258x359
1258x327
1258x343
File /var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_dbfs-noise.rrd not found! Associated graph will be empty!
1258x343
1258x327
1258x343
1258x343
1258x343
1258x343
1258x343
1258x343

**Comment by harkwoodservices** [comment]
Scratch that, re-edited the graphs1090, found some weird characters in the file.  Copied the default back over and it's running now.
Thanks for your help.

**Comment by wiedehopf** [comment]
So my fix fixed it?
Or only your edit?

**Comment by wiedehopf** [comment]
Weird characters in /etc/default/graphs1090 ?
Or /usr/share/graphs1090?

**Comment by harkwoodservices** [comment]
Your fix I think, I reverted the edit and it still failed.  Updated graphs1090 and it started running again.  Comments out of order a bit.

The odd characters were in /etc/default/graphs1090 so reset that to default.  No idea where they came from.

**Comment by wiedehopf** [comment]
Yeah so my fix probably didn't change anything and it was the stuff in /etc/default/graphs1090 from the start.

The change i made doesn't hurt though :)

Good day!
