### ISSUE TITLE
Maximum message rate 8000/sec ? 

### ISSUE THREAD

**Issue by phmlr** [wiedehopf/graphs1090#80]
My Readsb is running with multiple receivers (+15) and is going above 8000 messages/sec, but the graph stops at 7998. 
I already changed the "ul_message_rate=15000" in /etc/default/graphs1090, but this is not the solution. 

Is there something else that needs to be changed? 
![image](https://github.com/wiedehopf/graphs1090/assets/16925875/11aacc17-1cba-4d6c-af95-7c08761e041f)
![image](https://github.com/wiedehopf/graphs1090/assets/16925875/dc2c927e-91a8-4fb0-95b8-4fe9ee52f0f1)

**Comment by RundesBalli** [comment]
That was something we've encountered in our [Bratwurst](https://info.bratwurst.network/) project, because even with reduced messages from the feeders, we've got 45-50.000 messages per second.

```bash
sudo nano /usr/share/graphs1090/dump1090.db
```

Change the following:
```
dump1090_messages	value:DERIVE:0:100000
```

And apply the changes:
```
sudo /usr/share/graphs1090/new-format.sh
```

Hope that helps :)

**Comment by phmlr** [comment]
Tnx [RundesBalli](https://github.com/RundesBalli) !

This is indeed the solution.

**Comment by RundesBalli** [comment]
> Tnx [RundesBalli](https://github.com/RundesBalli) !
> 
> This is indeed the solution.

You're welcome :) Maybe you If you're already aggregating data on such a large scale, perhaps our project linked above might be of interest to you too :)
