### ISSUE TITLE
Missing Disk I/Os after switching to NVMe

### ISSUE THREAD

**Issue by d4niel-P** [wiedehopf/graphs1090#81]
logs: https://pastebin.com/32zqyvNs
script output: https://pastebin.com/NswxYt1G
platform: Linux raspberrypi 6.6.28+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux

Hi, readings of both I/Os disappeared after I cloned SD to NVMe, 'Disk Usage' graph shows correct values.

![obraz](https://github.com/wiedehopf/graphs1090/assets/4502783/221e27f3-17ed-4ea6-b7a5-11419acbdd66)
![obraz](https://github.com/wiedehopf/graphs1090/assets/4502783/d8037c0a-e9c0-46e5-9a6a-f043a0e11596)
![obraz](https://github.com/wiedehopf/graphs1090/assets/4502783/c6322aaf-f7be-45f4-9ea5-7c8c317fa835)

Pls ignore empty date before noon yesterday, my RPi5 died so I had to change the board and I used the opportunity to finally upgrade to nvme. The only data on the graphs is from the half an hour Pi was still booting from SD.

**Comment by wiedehopf** [comment]
```
ls -d /run/collectd/localhost/disk*
```

Basically it grabs the first disk stats that are recorded.
I suppose i could check the mount point for / and make it choose by that.

Oh i forgot you can just choose what is displayed:
```
/etc/default/graphs1090
```
Like this i believe:
```
disk=sda
```

**Comment by d4niel-P** [comment]
> ```
> ls -d /run/collectd/localhost/disk*
> ```
> 
> Basically it grabs the first disk stats that are recorded. I suppose i could check the mount point for / and make it choose by that.
> 
Oh, that makes sense
`/run/collectd/localhost/disk-mmcblk0  /run/collectd/localhost/disk-nvme0n1  /run/collectd/localhost/disk-sda`

> Oh i forgot you can just choose what is displayed:
> 
> ```
> /etc/default/graphs1090
> ```
> 
> Like this i believe:
> 
> ```
> disk=sda
> ```
Welp. now I feel stupid. ;) I saw earlier that disk= is empty but populated 'Disk Usage' threw me off the scent and convinced that also I/Os from correct disk are displayed.
`disk=nvme0n1` fixed the issue. Thanks!
