### ISSUE TITLE
Gain Graph Update

### ISSUE THREAD

**Issue by victorengel** [wiedehopf/graphs1090#82]
My configuration had auto gain enabled. I disabled it, then tried various settings, restarting dump1090-fa. Looking at the map, I could see the changes were effective by how many aircraft were shown. However, the gain graph is not updating. I restarted graphs1090 just in case that were an issue.

I say the graph is not updating. However, what happened is that the graph simply ended. It now displays a numeric value of 49.6 while showing a horizontal line apparently at 49.6 that ends about half an hour ago, about when I started messing with gain. Current value is 48, confirmed by piaware-config -showall (and yes I restarted dump1090 each time). The other graphs, like message count, etc., all change as expected when I make a gain adjustment, but not the gain graph.
![Uploading Screen Shot 2024-05-06 at 8.04.41 PM.png…]()

**Comment by victorengel** [comment]
Hmm - do PNGs not work here? Let me try converting it to a jpeg.
![Gain Screen Shot](https://github.com/wiedehopf/graphs1090/assets/3145703/3b0fb149-0f3a-4e7b-8114-6c4c7787bf98)

**Comment by wiedehopf** [comment]
Run the graphs1090 install and see if that fixes it.

**Comment by victorengel** [comment]
Nope - and now (after waiting long enough for the graphs to update, it says Gain: nan
![Gain Screen](https://github.com/wiedehopf/graphs1090/assets/3145703/fdb3d73a-c8d5-496b-a07b-01519b443533)

**Comment by wiedehopf** [comment]
/run/dump1090-fa/stats.json

**Comment by victorengel** [comment]
No jq

**Comment by wiedehopf** [comment]
cat < /run/dump1090-fa/stats.json

You could have just installed jq ...

**Comment by victorengel** [comment]
{
"latest":{"start":1715104610.6,"end":1715104610.6,"local":{"samples_processed":0,"samples_dropped":0,"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0],"strong_signals":0,"gain_db":48.0},"remote":{"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0]},"cpr":{"surface":0,"airborne":0,"global_ok":0,"global_bad":0,"global_range":0,"global_speed":0,"global_skipped":0,"local_ok":0,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":0,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":0},"tracks":{"all":0,"single_message":0,"unreliable":0},"messages":0,"messages_by_df":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},
"last1min":{"start":1715104550.6,"end":1715104610.6,"local":{"samples_processed":144048128,"samples_dropped":0,"modeac":0,"modes":1164339,"bad":2656021,"unknown_icao":481040,"accepted":[9953,755],"signal":-11.7,"noise":-30.3,"peak_signal":-0.8,"strong_signals":358,"gain_db":48.0},"remote":{"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0]},"cpr":{"surface":0,"airborne":1631,"global_ok":1591,"global_bad":0,"global_range":0,"global_speed":0,"global_skipped":0,"local_ok":27,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":13,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":10974,"reader":3995,"background":602},"tracks":{"all":9,"single_message":4,"unreliable":4},"messages":10708,"messages_by_df":[2416,0,0,0,541,13,0,0,0,0,0,3161,0,0,0,0,106,4465,4,0,2,0,0,0,0,0,0,0,0,0,0,0]},
"last5min":{"start":1715104310.6,"end":1715104610.6,"local":{"samples_processed":719978496,"samples_dropped":0,"modeac":0,"modes":5825204,"bad":13294848,"unknown_icao":2400302,"accepted":[51861,3880],"signal":-11.8,"noise":-32.1,"peak_signal":-0.8,"strong_signals":2082,"gain_db":48.0},"remote":{"modeac":0,"modes":45,"bad":0,"unknown_icao":0,"accepted":[45,0]},"cpr":{"surface":0,"airborne":8432,"global_ok":8196,"global_bad":1,"global_range":0,"global_speed":0,"global_skipped":0,"local_ok":167,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":68,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":53804,"reader":19801,"background":3088},"tracks":{"all":34,"single_message":15,"unreliable":16},"messages":55786,"messages_by_df":[12843,0,0,0,2897,84,0,0,0,0,0,15913,0,0,0,0,601,23360,59,0,23,6,0,0,0,0,0,0,0,0,0,0]},
"last15min":{"start":1715103710.6,"end":1715104610.6,"local":{"samples_processed":2159935488,"samples_dropped":0,"modeac":0,"modes":17509395,"bad":39983708,"unknown_icao":7223322,"accepted":[144813,11064],"signal":-12.4,"noise":-32.9,"peak_signal":-0.8,"strong_signals":5517,"gain_db":48.0},"remote":{"modeac":0,"modes":93,"bad":0,"unknown_icao":0,"accepted":[93,0]},"cpr":{"surface":0,"airborne":23702,"global_ok":22975,"global_bad":1,"global_range":0,"global_speed":0,"global_skipped":1,"local_ok":548,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":178,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":162550,"reader":59750,"background":9240},"tracks":{"all":101,"single_message":46,"unreliable":49},"messages":155970,"messages_by_df":[37374,0,0,0,8413,234,0,0,0,0,0,42875,0,0,0,0,1466,65396,126,0,70,16,0,0,0,0,0,0,0,0,0,0]},
"total":{"start":1715042690.5,"end":1715104610.6,"local":{"samples_processed":148607860736,"samples_dropped":0,"modeac":0,"modes":1251002303,"bad":2881052398,"unknown_icao":516693345,"accepted":[4503290,365300],"signal":-12.6,"noise":-34.6,"peak_signal":-0.8,"strong_signals":136125,"gain_db":48.0},"remote":{"modeac":0,"modes":4713,"bad":0,"unknown_icao":0,"accepted":[4713,0]},"cpr":{"surface":1,"airborne":790703,"global_ok":766190,"global_bad":33,"global_range":14,"global_speed":0,"global_skipped":110,"local_ok":19265,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":5216,"local_range":2,"local_speed":14,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":11374270,"reader":4113246,"background":570605},"tracks":{"all":4692,"single_message":3033,"unreliable":3213},"messages":4873303,"messages_by_df":[920800,0,0,0,283050,9316,0,0,0,0,0,1438954,0,0,0,0,43428,2168233,6263,0,2908,351,0,0,0,0,0,0,0,0,0,0]}
}

**Comment by wiedehopf** [comment]
Run the graphs1090 install ... let's see if it's fixed.

dump1090-fa yet again changed where they put the gain in their stats.json

**Comment by victorengel** [comment]
I didn't see a change after a graphs1090 install so I did a sudo systemctl restart collectd and it updated the gain as expected after waiting a few minutes.
